trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  imageName: 'readme-app'
  DOCKER_BUILDKIT: 1
  nodeVersion: '12.x'

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: $(nodeVersion)
    displayName: 'install node.js'

  - task: Npm@1
    inputs:
    command: 'install'
    displayName: 'npm install'

  - task: Maven@3
    inputs:
      mavenPomFile: 'pom.xml'
      mavenOptions: '-Xmx1024m'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.8'
      jdkArchitectureOption: 'x64'
      publishJUnitResults: true
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      goals: 'package'

  - task: Docker@2
    displayName: Build an image
    inputs:
      repository: $(imageName)
      command: build
      Dockerfile: Dockerfile
