version: '3'

volumes:
  db-data:

services:
  db:
    image: postgres:13.1-alpine
    container_name: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    expose:
      - 5432
    ports:
      - 5432:5432
    #    env_file:
    #      - 'config/database.yml'
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=readmeapp_db
      - PGDATA=/var/lib/postgresql/data/pgdata
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

  app:
    image: 'webcane/readme-app-spring:latest'
    container_name: spring
    build:
      context: .
    expose:
      - "8080"
    ports:
      - "8080:8080"
    restart: always
    environment:
      - SPRING_PROFILES_ACTIVE=app,dev,management,oauth2,openapi
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/readmeapp_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create
    depends_on:
      - db

  ui:
    image: 'webcane/readme-app-angular:latest'
    container_name: angular
    build:
      context: ./angular
    expose:
      - "80"
    ports:
      - "4200:80"
    restart: always
    volumes:
      - type: bind
        source: ./angular/src/assets/config/envConfig.json
        target: /assets/config/envConfig.json
    depends_on:
      - app
