version: '3'

networks:
  default:
    name: readme-app-net
    driver: bridge

volumes:
  postgres-data:

services:
  db:
    image: postgres:13.1-alpine
    networks:
      - default
    container_name: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    expose:
      - 5432
    ports:
      - 5432:5432
    #    env_file:
    #      - 'config/database.yml'
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=readmeapp_db
      - PGDATA=/var/lib/postgresql/data/pgdata
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

  app:
    image: 'webcane/readme-app-spring:latest'
    networks:
      - default
    container_name: spring
    build:
      context: .
    expose:
      - "8080"
    ports:
      - "8080:8080"
    restart: always
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/readmeapp_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create
    depends_on:
      - db

  ui:
    image: 'webcane/readme-app-angular:latest'
    container_name: angular
    build:
      context: ./angular
    expose:
      - "80"
    ports:
      - "4200:80"
    restart: always
    depends_on:
      - app
    