apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name }}
  labels:
    {{- include "app.selectorLabels" . | nindent 4 }}
    {{- include "readme-app.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.app.replicaCount }}
  selector:
    matchLabels:
      {{- include "app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "app.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: spring
          image: "{{ .Values.app.image.repository }}:{{ .Values.app.image.tag }}"
          imagePullPolicy: {{ .Values.app.image.pullPolicy }}
          ports:
            - name: "app"
              containerPort: {{ .Values.app.service.targetPort }}
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ template "readme-app.name" . }}-env
            - secretRef:
                name: {{ template "readme-app.name" . }}-env
          volumeMounts:
            - name: configmap-volume
              # Note: 'app.jar' currently resides within the root folder.
              mountPath: /config
              readOnly: true
      volumes:
        - name: configmap-volume
          configMap:
            name: {{ template "app.name" . }}
            items:
                - key: application.yml
                  path: application.yml