apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "readme-app.fullname" . }}-app-configmap
  labels:
    {{- include "readme-app.labels" . | nindent 4 }}
data:
  application.yml: |-
    spring.datasource.url: "jdbc:postgresql://{{ template "postgresql.hostname" . }}:{{- .Values.postgresql.service.port -}}/{{- .Values.postgresql.postgresqlDatabase -}}"
{{ toYaml .Values.app.configuration | indent 4 }}
