apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}
  labels:
    {{- include "app.selectorLabels" . | nindent 4 }}
    {{- include "readme-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.app.service.type }}
  ports:
    - name: "app"
      port: {{ .Values.app.service.port }}
      protocol: TCP
      targetPort: {{ .Values.app.service.targetPort }}
  selector:
    {{- include "app.selectorLabels" . | nindent 4 }}
