apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "ui.name" . }}
  labels:
    {{- include "readme-app.labels" . | nindent 4 }}
data:
  envConfig.json: |-
{{ toJson .Values.ui.configuration | indent 4 }}