apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.ui.name }}
  labels:
    {{- include "ui.selectorLabels" . | nindent 4 }}
      {{- include "readme-app.labels" . | nindent 4 }}
spec:
  ports:
    - name: "ui"
      port: {{ .Values.ui.service.port }}
      protocol: TCP
      targetPort: {{ .Values.ui.service.targetPort }}
  selector:
    {{- include "ui.selectorLabels" . | nindent 4 }}
