server:
  port: 8080
  #  servlet:
  #    context-path: /api
  error:
    whitelabel:
      enabled: false

logging:
  level:
    web: DEBUG
    org.hibernate.sql: DEBUG
    org.springframework: INFO
    org.springframework.web: DEBUG
#    org.springframework.orm.jpa: DEBUG
    org.springframework.security: DEBUG
#    org.springframework.transaction: DEBUG
#    org.springframework.transaction.interceptor: TRACE
    cane.brothers: DEBUG
    cane.brothers.spring.FilterableHttpTraceFilter: TRACE


spring:
  main:
    banner-mode: "off"

  devtools:
    restart:
      enabled: true

#  resources:
#    add-mappings: false

#  mvc:
#    throw-exception-if-no-handler-found: true