app:
  auth:
    cookieExpiration: 1h
    tokenAudience: local
    tokenSubject: readme-app
    tokenExpiration: 1d # 86400000ms
    tokenSecret: topsecret
  oauth2:
    # After successfully authenticating with the OAuth2 Provider,
    # we'll be generating an auth token for the user and sending the token to the
    # redirectUri mentioned by the frontend client in the /oauth2/authorize request.
    # We're not using cookies because they won't work well in mobile clients.
    authorizedRedirectUri: "http://localhost:4200/oauth2/redirect"
