spring:
  security:
    oauth2:
      client:
        registration:
          github:
# see env variables
#            clientId: 
#            clientSecret: 
            redirectUri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - user:email
              - read:user
