spring:
  # Database
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/radb
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    generate-ddl: true
    open-in-view: false
    hibernate:
      ddl-auto: create # When you launch the application for the first time - switch "update" at "create" ("create-drop")
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
