spring:
  security:
    basic:
      enabled: false
    #    user:
    #      name: cane

    oauth2:
      client:
        registration:
          github:
            clientId: ${client.id}
            clientSecret: ${client.secret}
            redirectUri: "{baseUrl}/oauth2/callback/github"
#            redirectUri: "{baseUrl}"
#            scope:
#            - user:email
#            - read:user

#server:
#  forward-headers-strategy: FRAMEWORK