server:
  port: 3000

#management:
#  endpoints.web.cors:
#    allowed-origins: http://localhost:5000

spring:
  main:
    banner-mode: "off"

  datasource:
    url: jdbc:h2:mem:radb;DB_CLOSE_DELAY=-1

  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
      dialect: org.hibernate.dialect.H2Dialect

  h2:
    console:
      enabled: true

logging:
  level:
    org:
      springframework: ERROR
    cane:
      brothers: DEBUG