server:
  port: 3000
  #  servlet:
  #    context-path: /api
  error:
    whitelabel:
      enabled: false

#management:
#  endpoints.web.cors:
#    allowed-origins: http://localhost:5000

spring:
  main:
    banner-mode: "off"

  datasource:
    url: jdbc:h2:mem:radb;DB_CLOSE_DELAY=-1

  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
      dialect: org.hibernate.dialect.H2Dialect

    open-in-view: false

  h2:
    console:
#      path: /h2-console
      enabled: true

  devtools:
    restart:
      enabled: true

springfox:
  documentation:
    swagger:
      v2:
        # default mapped URL path "/v2/api-docs"
        path: "/swagger"

logging:
  level:
    org:
      springframework: INFO
    cane:
      brothers: DEBUG