spring:
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: ${client.id}
            clientSecret: ${client.secret}
            redirectUri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - user:email
              - read:user
