management:
  endpoint:
    httptrace:
      enabled: true
  endpoints:
    #    enabled-by-default: true
    base-path: /management
    web:
      exposure:
        # include: httptrace,env,info,health,metrics,conditions,beans,configprops #, env, httptrace, routes, beans
        include: '*' #, env, httptrace, routes, beans
#     cors:
#       allowed-origins: http://localhost:5000