server:
  port: 3000
  #  servlet:
  #    context-path: /api
  error:
    whitelabel:
      enabled: false

logging.level:
  web: DEBUG
  org.springframework: INFO
  org.springframework.web: DEBUG
  org.springframework.security: DEBUG
  cane.brothers: DEBUG
  cane.brothers.spring.FilterableHttpTraceFilter: TRACE


spring:
  main:
    banner-mode: "off"

  devtools:
    restart:
      enabled: true

#  resources:
#    add-mappings: false

#  mvc:
#    throw-exception-if-no-handler-found: true