app:
  auth:
    # see env var
    #    tokenSecret:
    tokenExpiration: 864000000ms
    cookieExpiration: 180s
  oauth2:
    # After successfully authenticating with the OAuth2 Provider,
    # we'll be generating an auth token for the user and sending the token to the
    # redirectUri mentioned by the frontend client in the /oauth2/authorize request.
    # We're not using cookies because they won't work well in mobile clients.
    authorizedRedirectUris:
      - http://localhost:4200/oauth2/redirect
      - myandroidapp://oauth2/redirect
      - myiosapp://oauth2/redirect
  url: @project.url@
  name: @project.name@
  version: @project.version@
  description: @project.description@
  email: @project.developers[0].email@
