spring:
  profiles:
    active: swagger,dev
  main:
    banner-mode: "off"

  datasource:
    url: jdbc:h2:mem:radb;DB_CLOSE_DELAY=-1

  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
      dialect: org.hibernate.dialect.H2Dialect

    open-in-view: false

  h2:
    console:
      #      path: /h2-console
      enabled: true

  devtools:
    restart:
      enabled: true

#  resources:
#    add-mappings: false

#  mvc:
#    throw-exception-if-no-handler-found: true

server:
  port: 3000
  #  servlet:
  #    context-path: /api
  error:
    whitelabel:
      enabled: false

springfox:
  documentation:
    swagger:
      v2:
        # default mapped URL path "/v2/api-docs"
        path: "/swagger"

logging:
  level:
    org:
      springframework: INFO
    cane:
      brothers: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: info, health, metrics, httptrace
#     cors:
#       allowed-origins: http://localhost:5000