# config file version
apiVersion: 1

datasources:
  - name: Prometheus
    access: proxy
    type: prometheus
    url: http://prometheus:9090
    isDefault: true
    orgId: 1
    editable: false
    version: 1