apiVersion: v1
kind: Service
metadata:
  name: app
  labels:
    io.kompose.service: app
spec:
  type: ClusterIP
  ports:
    - name: app
      port: {{ .Values.app.port }}
      targetPort: {{ .Values.app.port }}
  selector:
    io.kompose.service: app
