apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}
  labels:
    io.kompose.service: {{ .Values.app.name }}
spec:
  type: ClusterIP
  ports:
    - name: "app"
      port: {{ .Values.app.port }}
      targetPort: {{ .Values.app.port }}
  selector:
    io.kompose.service: {{ .Values.app.name }}
