apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.db.name }}
  labels:
    io.kompose.service: {{ .Values.db.name }}
    app.kubernetes.io/component: postgres
spec:
  type: ClusterIP
  ports:
    - name: "db"
      port: {{ .Values.db.port }}
      targetPort: {{ .Values.db.port }}
  selector:
    io.kompose.service: {{ .Values.db.name }}
    app.kubernetes.io/name: {{ .Values.db.name }}
    app.kubernetes.io/instance: {{ .Release.Name }}

