apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: readme-app
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - host: locahost
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ui
                port:
                  number: {{ .Values.ui.port }}