apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui
  labels:
    io.kompose.service: ui
spec:
  replicas: {{ .Values.ui.replicaCount }}
  selector:
    matchLabels:
      io.kompose.service: ui
  template:
    metadata:
      labels:
        io.kompose.service: ui
    spec:
      containers:
        - name: angular
          image: {{ .Values.ui.image }}:{{ .Values.tag }}
          ports:
              - containerPort: {{ .Values.ui.port }}
      restartPolicy: Always
