apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: ui
  name: ui
spec:
  ports:
    - name: "ui"
      port: 4200
      targetPort: {{ .Values.app.port }}
  selector:
    io.kompose.service: ui
