nameOverride: ""
fullnameOverride: ""

app:
  name: readme-app-api
  replicaCount: 1
  image:
    repository: webcane/readme-app-spring
    # "Always"
    pullPolicy: IfNotPresent
    tag: "latest"
  service:
    type: ClusterIP
    port: 8080
    targetPort: 8080
  nameOverride: ""

ui:
  name: readme-app-ui
  replicaCount: 1
  image:
    repository: webcane/readme-app-angular
    pullPolicy: IfNotPresent
    tag: "latest"
  service:
    type: ClusterIP
    port: 4200
    targetPort: 80
  nameOverride: ""

## Postgres chart configuration
## https://github.com/helm/charts/blob/master/stable/postgresql/values.yaml

postgresql:
  ## Whether to deploy the Postgres Chart or not
  enabled: true
  ## PostgreSQL service configuration
  service:
    port: 5432
  postgresqlUsername: postgres
  postgresqlPassword: postgres
  postgresqlDatabase: readmeapp_db
  postgresqlConfiguration:
  ## Disable Postgres Persistence
  persistence:
    enabled: false
#  initdbScripts:
#db:
#  name: readme-app-db
#  replicaCount: 1
#  image: postgres:13.1-alpine
#  port: 5432

ingress:
  enabled: true
  annotations: {}
  nginx.ingress.kubernetes.io/rewrite-target: /$1
  # kubernetes.io/ingress.class: nginx
  # kubernetes.io/tls-acme: "true"
  hosts:
    - host: kubernetes.docker.internal
      paths: 
        - path: /
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

  #Spring related config to helm chart
configuration:
  spring:
    datasource: 
      username: postgres
      password: postgres
      platform: postgresql
      driver-class-name: org.postgresql.Driver
    jpa:
      showsql: true
      generateddl: true
      open-in-view: false
      hibernate:
        ddlAuto: update #create #validate
      database: postgresql
      database-platform: org.hibernate.dialect.PostgreSQLDialect